#!/bin/sh


# Tạo Package
apt-ftparchive packages ./debs > ./Packages;
#sed -i -e '/^SHA/d' ./Packages;

# Tạo Package.bz2
bzip2 -c9k ./Packages > ./Packages.bz2;

# Tạo Release

printf "Origin: FAHLNBG Repo\nLabel: FAHLNBG\nSuite: stable\nVersion: 1.0\nCodename: ios\nArchitecture: iphoneos-arm\nComponents: main\nDescription: Source Cydia Repo by FAHLNBG\nMD5Sum:\n "$(cat ./Packages | md5sum | cut -d ' ' -f 1)" "$(stat ./Packages --printf="%s")" Packages\n "$(cat ./Packages.bz2 | md5sum | cut -d ' ' -f 1)" "$(stat ./Packages.bz2 --printf="%s")" Packages.bz2\n" >Release;
exit 0;
