name: Complete & Update souce package

on:
  workflow_dispatch:

jobs:
  FAHLNBG-with-love:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Dependencies
        run: |
          if [ -f "./apt-ftparchive" ]; then
            chmod +x apt-ftparchive
            else echo "Dependencies apt-ftparchive ... PLEASE!!!"
          fi


          
      - name: Delete old file
        run: rm -R Packages Packages.bz2 Release
          
      - name: Creat new file Packages , Packages.bz2
        run: |
          apt-ftparchive packages ./debs > ./Packages
          bzip2 -c9k ./Packages > ./Packages.bz2
     
      - name: Creat new file Release
        run: |
          echo "Origin: FAHLNBG Repo
          Label: FAHLNBG
          Suite: stable
          Version: 1.0
          Codename: ios
          Architectures: iphoneos-arm iphoneos-arm64
          Components: main
          Description: Source Repo by github-action <fahlnbg>
          MD5Sum:" > Release

          # Tính toán checksum và kích thước cho tệp Packages
          printf "%s\n" "$(md5sum ./Packages | cut -d ' ' -f 1) $(stat --format="%s" ./Packages) Package" >> Release
          printf "%s" "$(md5sum ./Packages.bz2 | cut -d ' ' -f 1) $(stat --format="%s" ./Packages.bz2) Package.bz2" >> Release


  Deloy-Push:
    runs-on: ubuntu-latest

    steps:
      - name: Upload
        run: |
          git add --all
          git config --global user.name 'FAHLNBG'
          git config --global user.email 'fahlnbg@gmail.com'
          git commit -m "Push Repo"
          git push -u origin master
          
