name: Convent Deb to iPa

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: remove pkgz
        run: |
          
          	rm -R Packages Packages.bz2 Release
          
          	apt-ftparchive packages ./debs > ./Packages;
          
          	bzip2 -c9k ./Packages > ./Packages.bz2; 
          
          	if [ -e "Rls" ]
          	then echo
          	else printf "Origin: GitPush Repo\nLabel: GitPush\nSuite: stable\nVersion: 1.0\nCodename: ios\nArchitectures: iphoneos-arm iphoneos-arm64\nComponents: main\nDescription: Source Cydia Repo by GitPush <fahlnbg>\n" > Rls;
          
          	sleep 2;
          	fi
          	# Tạo Release
          	printf "MD5Sum:\n "$(cat ./Packages | md5sum | cut -d ' ' -f 1)" "$(stat ./Packages --printf="%s")" Packages\n "$(cat ./Packages.bz2 | md5sum | cut -d ' ' -f 1)" "$(stat ./Packages.bz2 --printf="%s")" Packages.bz2\n" > Rls1;
          
          	cat Rls Rls1 > Release;
          	rm -R Rls1;





        
