
name: Template Cleanup
on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Clean secret management files
      run: |
        rm -f \
          Packages \
          .github/file2.yaml
    - name: Commit files and push it
      run: |
        git config --global user.email "email@gmail.com"
        git config --global user.name "github actions"
        git add --all
        git commit -m "chore: clean repo"
        git push
