
name: Template Cleanup
on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Clean secret management files
      run: |
        rm -f \
          Packages \
          Packages.bz2 \
          Release

    - name: Commit files and push it
            uses: actions/upload-artifact@v3.1.0
        with:
      run: |
        git config --global user.email "fahlnbg@gmail.com"
        git config --global user.name "github actions"
        git add .
        git commit -m "chore: clean repo"
        git push
