name: Delete File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'File path to delete'
        required: true
        default: 'Packages'

jobs:
  delete-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Delete file
      run: |
        FILE_PATH="${{ github.event.inputs.file }}"
        if [ -f "$FILE_PATH" ]; then
          rm "$FILE_PATH"
          echo "File deleted: $FILE_PATH"
        else
          echo "File not found: $FILE_PATH"
          exit 1
        fi
        
    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Delete file via GitHub Actions"
        git push
